unordered-result
{"a_ida":20,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":45,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":0,"b_days":5,"c_ida":0,"c_idb":0,"c_idc":0,"c_days":5,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0,"d2":19}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":0,"b_days":5,"c_ida":0,"c_idb":0,"c_idc":5,"c_days":5,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"d2":12}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":0,"b_days":5,"c_ida":0,"c_idb":0,"c_idc":5,"c_days":5,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10,"d2":17}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":10,"c_days":5,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15,"d2":12}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":10,"c_days":5,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20,"d2":13}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":15,"c_days":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":20,"c_days":5,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25,"d2":18}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":25,"c_days":5,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30,"d2":18}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":5,"b_days":5,"c_ida":0,"c_idb":5,"c_idc":25,"c_days":5,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":35,"d2":18}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":10,"b_days":5,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":15,"b_days":5,"c_ida":0,"c_idb":15,"c_idc":25,"c_days":5,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30,"d2":32}
{"a_ida":0,"a_days":5,"b_ida":0,"b_idb":15,"b_days":5,"c_ida":0,"c_idb":15,"c_idc":25,"c_days":5,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":35,"d2":37}
{"a_ida":60,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":75,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":85,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":35,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":65,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":80,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":10,"a_days":5,"b_ida":10,"b_idb":4,"b_days":5,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":30,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":5,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":25,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":55,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":15,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":50,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":90,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":70,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
{"a_ida":95,"a_days":5,"b_ida":null,"b_idb":null,"b_days":null,"c_ida":null,"c_idb":null,"c_idc":null,"c_days":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d2":null}
