unordered-result
{"a_ida":0,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":0,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0}
{"a_ida":0,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":5,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5}
{"a_ida":0,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":5,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":10,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":10,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":15,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":20,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":25,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30}
{"a_ida":0,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":25,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":35}
{"a_ida":0,"b_ida":0,"b_idb":10,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":0,"b_ida":0,"b_idb":15,"c_ida":0,"c_idb":15,"c_idc":25,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30}
{"a_ida":0,"b_ida":0,"b_idb":15,"c_ida":0,"c_idb":15,"c_idc":25,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":35}
{"a_ida":5,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":10,"b_ida":10,"b_idb":4,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":15,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":20,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":25,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":30,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":35,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":45,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":50,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":55,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":60,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":65,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":70,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":75,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":80,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":85,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":90,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"a_ida":95,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
