unordered-result
{"a_ida":20,"a_c1":-8,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":45,"a_c1":14,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":0,"b_c1":8,"c_ida":0,"c_idb":0,"c_idc":0,"c1":15,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0,"d1":25}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":0,"b_c1":8,"c_ida":0,"c_idb":0,"c_idc":5,"c1":25,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"d1":13}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":0,"b_c1":8,"c_ida":0,"c_idb":0,"c_idc":5,"c1":25,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10,"d1":24}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":10,"c1":25,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15,"d1":7}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":10,"c1":25,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20,"d1":33}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":15,"c1":25,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":20,"c1":25,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25,"d1":-3}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":25,"c1":25,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30,"d1":30}
{"a_ida":0,"a_c1":8,"b_ida":0,"b_idb":5,"b_c1":8,"c_ida":0,"c_idb":5,"c_idc":25,"c1":25,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":35,"d1":-3}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":6,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":7,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":8,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":9,"b_c1":null,"c_ida":40,"c_idb":9,"c_idc":5,"c1":5,"d_ida":40,"d_idb":9,"d_idc":5,"d_idd":30,"d1":9}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":9,"b_c1":null,"c_ida":40,"c_idb":9,"c_idc":6,"c1":6,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":35,"d1":2}
{"a_ida":40,"a_c1":14,"b_ida":40,"b_idb":9,"b_c1":null,"c_ida":40,"c_idb":9,"c_idc":6,"c1":6,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":45,"d1":1}
{"a_ida":60,"a_c1":881,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":75,"a_c1":23,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":85,"a_c1":18,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":35,"a_c1":20,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":65,"a_c1":35,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":80,"a_c1":37,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":10,"a_c1":18,"b_ida":10,"b_idb":4,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":30,"a_c1":12,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":5,"a_c1":8,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":25,"a_c1":12,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":55,"a_c1":80,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":15,"a_c1":28,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":50,"a_c1":8,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":90,"a_c1":8,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":70,"a_c1":35,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":95,"a_c1":-12,"b_ida":null,"b_idb":null,"b_c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
