unordered-result
{"a":{"ida":20,"a1":5,"a2":23,"c1":-8,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":45,"a1":10,"a2":-5,"c1":14,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":0,"b1":11,"b2":9,"c1":8},"c":{"ida":0,"idb":0,"idc":0,"c1":15,"c2":9,"c3":4,"str":"0_0_0_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                                                                                                       "},"d":{"ida":0,"idb":0,"idc":0,"idd":0,"d1":25,"d2":19,"c3":44,"str":"0_0_0_0_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                       "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":0,"b1":11,"b2":9,"c1":8},"c":{"ida":0,"idb":0,"idc":5,"c1":25,"c2":29,"c3":24,"str":"0_0_5_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj"},"d":{"ida":0,"idb":0,"idc":5,"idd":5,"d1":13,"d2":12,"c3":-4,"str":"0_0_5_5_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                   "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":0,"b1":11,"b2":9,"c1":8},"c":{"ida":0,"idb":0,"idc":5,"c1":25,"c2":29,"c3":24,"str":"0_0_5_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj"},"d":{"ida":0,"idb":0,"idc":5,"idd":10,"d1":24,"d2":17,"c3":32,"str":"0_0_5_10_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                    "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":10,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":5,"idc":10,"idd":15,"d1":7,"d2":12,"c3":-32,"str":"0_5_10_15_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                                                                                                          "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":10,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":5,"idc":10,"idd":20,"d1":33,"d2":13,"c3":2,"str":"0_5_10_20_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":15,"c1":25,"c2":29,"c3":24,"str":null},"d":null}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":20,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":5,"idc":20,"idd":25,"d1":-3,"d2":18,"c3":5,"str":"0_5_20_25_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                              "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":25,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":5,"idc":25,"idd":30,"d1":30,"d2":18,"c3":5,"str":"0_5_25_30_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                    "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":5,"b1":12,"b2":90,"c1":8},"c":{"ida":0,"idb":5,"idc":25,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":5,"idc":25,"idd":35,"d1":-3,"d2":18,"c3":5,"str":"0_5_25_35_kfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                    "}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":10,"b1":16,"b2":45,"c1":9},"c":null,"d":null}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":15,"b1":16,"b2":45,"c1":9},"c":{"ida":0,"idb":15,"idc":25,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":15,"idc":25,"idd":30,"d1":5,"d2":32,"c3":3,"str":null}}
{"a":{"ida":0,"a1":1,"a2":5,"c1":8,"str":"0_1_sghigdjkfsglkksjgijgpigljfdgldjgadjg;sjg;sjgsjgajfsgpdjgpjgpsjgpjgpsfaj                                                                                                                                                                                                                                                                     "},"b":{"ida":0,"idb":15,"b1":16,"b2":45,"c1":9},"c":{"ida":0,"idb":15,"idc":25,"c1":25,"c2":29,"c3":24,"str":null},"d":{"ida":0,"idb":15,"idc":25,"idd":35,"d1":5,"d2":37,"c3":32,"str":null}}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":0,"b1":16,"b2":9,"c1":9},"c":{"ida":40,"idb":0,"idc":0,"c1":5,"c2":9,"c3":24,"str":null},"d":null}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":5,"b1":12,"b2":9,"c1":8},"c":null,"d":null}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":6,"b1":null,"b2":null,"c1":null},"c":null,"d":null}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":7,"b1":null,"b2":null,"c1":null},"c":null,"d":null}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":8,"b1":null,"b2":null,"c1":null},"c":null,"d":null}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":9,"b1":null,"b2":null,"c1":null},"c":{"ida":40,"idb":9,"idc":5,"c1":5,"c2":-9,"c3":21,"str":null},"d":{"ida":40,"idb":9,"idc":5,"idd":30,"d1":9,"d2":-2,"c3":5,"str":null}}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":9,"b1":null,"b2":null,"c1":null},"c":{"ida":40,"idb":9,"idc":6,"c1":6,"c2":19,"c3":21,"str":null},"d":{"ida":40,"idb":9,"idc":6,"idd":35,"d1":2,"d2":20,"c3":5,"str":null}}
{"a":{"ida":40,"a1":9,"a2":35,"c1":14,"str":null},"b":{"ida":40,"idb":9,"b1":null,"b2":null,"c1":null},"c":{"ida":40,"idb":9,"idc":6,"c1":6,"c2":19,"c3":21,"str":null},"d":{"ida":40,"idb":9,"idc":6,"idd":45,"d1":1,"d2":2,"c3":-5,"str":null}}
{"a":{"ida":60,"a1":13,"a2":11,"c1":881,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":75,"a1":16,"a2":23,"c1":23,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":85,"a1":18,"a2":5,"c1":18,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":35,"a1":8,"a2":5,"c1":20,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":65,"a1":14,"a2":11,"c1":35,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":80,"a1":17,"a2":37,"c1":37,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":10,"a1":3,"a2":42,"c1":18,"str":null},"b":{"ida":10,"idb":4,"b1":null,"b2":null,"c1":null},"c":null,"d":null}
{"a":{"ida":30,"a1":7,"a2":5,"c1":12,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":5,"a1":2,"a2":35,"c1":8,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":25,"a1":6,"a2":-7,"c1":12,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":55,"a1":12,"a2":13,"c1":80,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":15,"a1":4,"a2":-7,"c1":28,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":50,"a1":11,"a2":17,"c1":8,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":90,"a1":19,"a2":23,"c1":8,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":70,"a1":15,"a2":21,"c1":35,"str":null},"b":null,"c":null,"d":null}
{"a":{"ida":95,"a1":20,"a2":8,"c1":-12,"str":null},"b":null,"c":null,"d":null}
