unordered-result
{"a_ida":20,"a1":5,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":45,"a1":10,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":0,"b1":11,"c1":8,"c_ida":0,"c_idb":0,"c_idc":5,"c2":29,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"d1":13}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"b1":12,"c1":8,"c_ida":0,"c_idb":5,"c_idc":10,"c2":29,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15,"d1":7}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"b1":12,"c1":8,"c_ida":0,"c_idb":5,"c_idc":15,"c2":29,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"b1":12,"c1":8,"c_ida":0,"c_idb":5,"c_idc":20,"c2":29,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25,"d1":-3}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"b1":12,"c1":8,"c_ida":0,"c_idb":5,"c_idc":25,"c2":29,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":35,"d1":-3}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":10,"b1":16,"c1":9,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":15,"b1":16,"c1":9,"c_ida":0,"c_idb":15,"c_idc":25,"c2":29,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30,"d1":5}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":15,"b1":16,"c1":9,"c_ida":0,"c_idb":15,"c_idc":25,"c2":29,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":35,"d1":5}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":0,"b1":16,"c1":9,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":5,"b1":12,"c1":8,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":6,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":7,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":8,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":40,"a1":9,"b_ida":40,"b_idb":9,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":60,"a1":13,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":75,"a1":16,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":85,"a1":18,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":35,"a1":8,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":65,"a1":14,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":80,"a1":17,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":10,"a1":3,"b_ida":10,"b_idb":4,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":30,"a1":7,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":5,"a1":2,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":25,"a1":6,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":55,"a1":12,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":15,"a1":4,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":50,"a1":11,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":90,"a1":19,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":70,"a1":15,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
{"a_ida":95,"a1":20,"b_ida":null,"b_idb":null,"b1":null,"c1":null,"c_ida":null,"c_idb":null,"c_idc":null,"c2":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"d1":null}
