unordered-result
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":0,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":5,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":6,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":7,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":2,"e_ide":0,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":15,"e_ide":25,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":15,"e_ide":35,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":0,"f_idf":0,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":0,"f_idf":10,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":0,"j_idg":15,"j_idj":25,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":0,"j_idg":15,"j_idj":35,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":10,"j_idg":15,"j_idj":35,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":10,"j_idg":15,"j_idj":45,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":15,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":20,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":25,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":30,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":35,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":40,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":50,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":0,"e_ide":7,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":0,"e_ide":8,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":1,"e_ide":7,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":2,"d_idc":5,"d_idd":5,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":3,"d_idc":6,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":4,"e_ide":7,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":25,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":5,"e_ide":25,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":5,"e_ide":35,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":20,"d_idd":25,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":25,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":35,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":45,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":8,"e_ide":25,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":8,"e_ide":35,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":25,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":35,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":45,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":55,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":3,"j_idj":25,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":3,"j_idj":35,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":40,"h_idg":5,"h_idh":35}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":40,"h_idg":7,"h_idh":35}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":8,"j_idj":25,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":8,"j_idj":35,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":15,"j_idj":25,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":40,"j_idg":15,"j_idj":35,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":40,"h_idg":15,"h_idh":35}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":40,"h_idg":15,"h_idh":45}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":40,"h_idg":15,"h_idh":46}
{"a_ida":45,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":50,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":55,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":60,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":65,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":70,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":75,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":80,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":85,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":90,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
{"a_ida":95,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null,"f_ida":null,"f_idf":null,"j_ida":null,"j_idg":null,"j_idj":null,"h_ida":null,"h_idg":null,"h_idh":null}
