unordered-result
{"a_ida":75,"a2":23,"a1":16,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":20,"a2":23,"a1":5,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":90,"a2":23,"a1":19,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":70,"a2":21,"a1":15,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":50,"a2":17,"a1":11,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":55,"a2":13,"a1":12,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":65,"a2":11,"a1":14,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":60,"a2":11,"a1":13,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":95,"a2":8,"a1":20,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":85,"a2":5,"a1":18,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":35,"a2":5,"a1":8,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":0,"c1":15,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":5,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":10,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":15,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":20,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":25,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":10,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a2":5,"a1":1,"b_ida":0,"b_idb":15,"c_ida":0,"c_idb":15,"c_idc":25,"c1":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":30,"a2":5,"a1":7,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":45,"a2":-5,"a1":10,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":25,"a2":-7,"a1":6,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":15,"a2":-7,"a1":4,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"c1":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
