unordered-result
{"id":22,"state":"OR"}
{"id":23,"state":"OR"}
{"id":24,"state":"OR"}
{"id":28,"state":"OR"}
{"id":2,"state":"OR"}
{"id":25,"state":"OR"}
{"id":6,"state":"NY"}
{"id":1,"state":"MA"}
{"id":5,"state":"MA"}
{"id":4,"state":"MA"}
{"id":0,"state":"CA"}
{"id":7,"state":"CA"}
{"id":21,"state":""}
