unordered-result
{"id":0,"state":"CA"}
{"id":7,"state":"CA"}
{"id":8,"state":"CA"}
{"id":1,"state":"MA"}
{"id":4,"state":"MA"}
{"id":5,"state":"MA"}
{"id":6,"state":"NY"}
{"id":2,"state":"OR"}
{"id":3,"state":"WA"}
{"id":10,"state":null}
{"id":11,"state":null}
{"id":15,"state":null}
{"id":16,"state":null}
{"id":17,"state":null}
{"id":9,"state":null}
{"id":12,"state":null}
{"id":13,"state":null}
{"id":14,"state":null}
