unordered-result
{"id":6,"record":{"long":null,"int":null,"string":"ef","bool":true,"float":3.0}}
{"id":8,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":9,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":11,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":12,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":13,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":14,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":16,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":1,"record":{"long":50,"int":20,"string":"xyz","bool":true,"float":3.0}}
{"id":3,"record":{"long":10,"int":200,"string":"tr","bool":true,"float":3.0}}
{"id":10,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":15,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":17,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0}}
{"id":7,"record":{"long":1,"int":-20,"string":"xyz","bool":true,"float":30.0}}
{"id":2,"record":{"long":50,"int":50,"string":"abc","bool":false,"float":33.0}}
