unordered-result
{"id1":1,"atomic_cnt":1}
{"id1":2,"atomic_cnt":1}
{"id1":3,"atomic_cnt":null}
{"id1":4,"atomic_cnt":null}
{"id1":5,"atomic_cnt":null}
{"id1":6,"atomic_cnt":null}
{"id1":7,"atomic_cnt":null}
{"id1":8,"atomic_cnt":null}
{"id1":9,"atomic_cnt":null}
{"id1":10,"atomic_cnt":null}