unordered-result
{"id1":1,"MSD_min":null}
{"id1":2,"MSD_min":null}
{"id1":3,"MSD_min":null}
{"id1":4,"MSD_min":-1}
{"id1":5,"MSD_min":null}
{"id1":6,"MSD_min":null}
{"id1":7,"MSD_min":null}
{"id1":8,"MSD_min":null}
{"id1":9,"MSD_min":null}
{"id1":10,"MSD_min":null}
