unordered-result
{"id1":1,"MSD_max":null}
{"id1":2,"MSD_max":null}
{"id1":3,"MSD_max":null}
{"id1":4,"MSD_max":true}
{"id1":5,"MSD_max":null}
{"id1":6,"MSD_max":null}
{"id1":7,"MSD_max":null}
{"id1":8,"MSD_max":null}
{"id1":9,"MSD_max":null}
{"id1":10,"MSD_max":null}
