unordered-result
{"id":5,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":9,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":3,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":10,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":8,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":4,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":1,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":6,"Column_2":null,"Column_3":null,"Column_4":null}
{"id":7,"Column_2":0,"Column_3":0,"Column_4":null}
