/*-
 * Copyright (C) 2011, 2025 Oracle and/or its affiliates. All rights reserved.
 *
 * This file was distributed by Oracle as part of a version of Oracle NoSQL
 * Database made available at:
 *
 * http://www.oracle.com/technetwork/database/database-technologies/nosqldb/downloads/index.html
 *
 * Please see the LICENSE file included in the top-level directory of the
 * appropriate version of Oracle NoSQL Database for a copy of the license and
 * additional information.
 */

package oracle.kv.txn;

/**
 * Interface that represents a transaction id. The transaction id is a
 * store-wide unique id associated with a particular transaction.
 */
public interface TransactionId {

    /**
     * @return the id of shard where the transaction is performed
     */
    int getShardId();

    /**
     * @return the transaction id generated by internal JE env
     */
    long getShardTxnId();

    /**
     * @return the timestamp of the transaction, which is from the entry of
     * commit (abort) for committed (aborted) transaction.
     */
    long getTimestamp();
}
