unordered-result
{"msgid":10,"sender":"markos"}
{"msgid":20,"sender":"markos"}
{"msgid":30,"sender":"george"}
{"msgid":40,"sender":"yev"}
{"msgid":50,"sender":"markos"}
{"msgid":60,"sender":"john"}
{"msgid":70,"sender":"george"}
{"msgid":80,"sender":"tim"}
{"msgid":90,"sender":"sam"}
{"msgid":100,"sender":"linda"}
