unordered-result
{"u_uid":1,"sender":"george","cnt":2}
{"u_uid":1,"sender":"john","cnt":1}
{"u_uid":1,"sender":"linda","cnt":1}
{"u_uid":1,"sender":"markos","cnt":3}
{"u_uid":1,"sender":"sam","cnt":1}
{"u_uid":1,"sender":"tim","cnt":1}
{"u_uid":1,"sender":"yev","cnt":1}
{"u_uid":2,"sender":null,"cnt":0}
{"u_uid":3,"sender":null,"cnt":0}
{"u_uid":4,"sender":null,"cnt":0}
{"u_uid":5,"sender":null,"cnt":0}
{"u_uid":6,"sender":null,"cnt":0}
{"u_uid":7,"sender":null,"cnt":0}
{"u_uid":8,"sender":null,"cnt":0}
{"u_uid":9,"sender":null,"cnt":0}
{"u_uid":10,"sender":null,"cnt":0}
{"u_uid":11,"sender":null,"cnt":0}
{"u_uid":12,"sender":null,"cnt":0}
{"u_uid":13,"sender":null,"cnt":0}
