unordered-result
{"bar1":1,"sum":null}
{"bar1":2,"sum":null}
{"bar1":3,"sum":null}
{"bar1":4,"sum":null}
{"bar1":5,"sum":null}
{"bar1":6,"sum":null}
{"bar1":7,"sum":null}
{"bar1":8,"sum":null}
{"bar1":9,"sum":null}
{"bar1":null,"sum":null}
