unordered-result
{"company_id":1,"department_id":1,"team_id":1,"emp_id":1,"project_id":1}
{"company_id":1,"department_id":1,"team_id":1,"emp_id":1,"project_id":2}
{"company_id":1,"department_id":1,"team_id":1,"emp_id":1,"project_id":5}
{"company_id":2,"department_id":1,"team_id":1,"emp_id":1,"project_id":3}
{"company_id":2,"department_id":1,"team_id":1,"emp_id":1,"project_id":4}
{"company_id":2,"department_id":2,"team_id":2,"emp_id":2,"project_id":7}
{"company_id":3,"department_id":1,"team_id":1,"emp_id":1,"project_id":5}
{"company_id":3,"department_id":1,"team_id":1,"emp_id":1,"project_id":7}
{"company_id":3,"department_id":2,"team_id":2,"emp_id":2,"project_id":5}
