#TestDescription: pattern length = 512 chars

select id, name 
from playerinfo p
where regex_like(p.profile,"onszgjnljuciohykubezpakgikaihirfxitsnrglxbyxfphdmwhswdguehawmouryeryjhjkhnadygvjuoedzgzbxuzqwcnwbwnjmzibnjzeujcqwuliibaobrkovnjbxuzaxlfscderdsdbetayyevjwzjqelcxkeajbziqkidipzfmkgvikvnouhbjdvlpztpzbqgyssnwwhcuqcouywqldsghatyskabxsxpfmaimtvlkebjgglzaurhyciczlwhwexxgkqpblxlepjxkpgqypymgzlhrdjmzxamgkaghcemtvktuirixhueqdqgdvxthtodzrsnhmxzmezgsggakiabmxnrjjgqnjequobciipaqyjsybvoyfwpmfddwbnquhjcpsaxnkpjymjftunzseotrhysghzcziwgnmnebjahxhwryxgjwjkmkfoqrsruonguoqtnnnsomhslflttupgtqyqpngvczmfcakssxymzqaniaafydzwrfshzo")