#TestDescription: pattern length = 512 chars
#Expected result: return true

select id1, name 
from  playerinfo  
where regex_like(profile,"onszgjnljuciohykubezpakgikaihirfxitsnrglxbyxfphdmwhswdguehawmouryeryjhjkhnadygvjuoedzgzbxuzqwcnwbwnjmzibnjzeujcqwuliibaobrkovnjbxuzaxlfscderdsdbetayyevjwzjqelcxkeajbziqkidipzfmkgvikvnouhbjdvlpztpzbqgyssnwwhcuqcouywqldsghatyskabxsxpfmaimtvlkebjgglzaurhyciczlwhwexxgkqpblxlepjxkpgqypymgzlhrdjmzxamgkaghcemtvktuirixhueqdqgdvxthtodzrsnhmxzmezgsggakiabmxnrjjgqnjequobciipaqyjsybvoyfwpmfddwbnquhjcpsaxnkpjymjftunzseotrhysghzcziwgnmnebjahxhwryxgjwjkmkfoqrsruonguoqtnnnsomhslflttupgtqyqpngvczmfcakssxymzqaniaafydzwrfshzo")