unordered-result
{"a_ida":0,"c_ida":0,"c_idb":0,"c_idc":0}
{"a_ida":0,"c_ida":0,"c_idb":0,"c_idc":5}
{"a_ida":0,"c_ida":0,"c_idb":3,"c_idc":10}
{"a_ida":0,"c_ida":0,"c_idb":5,"c_idc":10}
{"a_ida":0,"c_ida":0,"c_idb":5,"c_idc":15}
{"a_ida":0,"c_ida":0,"c_idb":5,"c_idc":20}
{"a_ida":0,"c_ida":0,"c_idb":5,"c_idc":25}
{"a_ida":0,"c_ida":0,"c_idb":15,"c_idc":25}
{"a_ida":5,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":10,"c_ida":10,"c_idb":8,"c_idc":10}
{"a_ida":15,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":20,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":25,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":30,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":35,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":45,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":50,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":55,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":60,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":65,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":70,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":75,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":80,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":85,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":90,"c_ida":null,"c_idb":null,"c_idc":null}
{"a_ida":95,"c_ida":null,"c_idb":null,"c_idc":null}
