unordered-result
{"areacode":118,"kind":"work","cnt":1}
{"areacode":304,"kind":"work","cnt":1}
{"areacode":400,"kind":"home","cnt":2}
{"areacode":400,"kind":"work","cnt":1}
{"areacode":404,"kind":"home","cnt":1}
{"areacode":408,"kind":"home","cnt":3}
{"areacode":408,"kind":"work","cnt":2}
{"areacode":450,"kind":"home","cnt":1}
{"areacode":460,"kind":"work","cnt":1}
{"areacode":500,"kind":"home","cnt":2}
{"areacode":500,"kind":"work","cnt":2}
{"areacode":510,"kind":"home","cnt":1}
{"areacode":520,"kind":"home","cnt":1}
{"areacode":600,"kind":"work","cnt":1}
{"areacode":605,"kind":"home","cnt":1}
{"areacode":605,"kind":"work","cnt":1}
{"areacode":610,"kind":"home","cnt":1}
{"areacode":610,"kind":"work","cnt":1}
{"areacode":629,"kind":"work","cnt":1}
{"areacode":650,"kind":"work","cnt":4}
{"areacode":null,"kind":"home","cnt":1}
{"areacode":null,"kind":null,"cnt":2}
