unordered-result
{"areacode":118,"min":"work"}
{"areacode":304,"min":"work"}
{"areacode":400,"min":"home"}
{"areacode":404,"min":"home"}
{"areacode":408,"min":"home"}
{"areacode":415,"min":null}
{"areacode":450,"min":"home"}
{"areacode":460,"min":"work"}
{"areacode":500,"min":"home"}
{"areacode":510,"min":"home"}
{"areacode":520,"min":"home"}
{"areacode":580,"min":null}
{"areacode":600,"min":"work"}
{"areacode":605,"min":"home"}
{"areacode":610,"min":"home"}
{"areacode":629,"min":"work"}
{"areacode":650,"min":"work"}
{"areacode":null,"min":"home"}
{"areacode":null,"min":null}
