unordered-result
{"id":0,"Column_2":2}
{"id":1,"Column_2":null}
{"id":2,"Column_2":null}
{"id":3,"Column_2":null}
{"id":4,"Column_2":2}
{"id":5,"Column_2":null}
{"id":6,"Column_2":1}
{"id":7,"Column_2":null}
