unordered-result
{"Column_1":null,"Column_2":null,"Column_3":null,"Column_4":null}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":null,"Column_2":null,"Column_3":null,"Column_4":null}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":true,"Column_2":true,"Column_3":true,"Column_4":true}
{"Column_1":null,"Column_2":null,"Column_3":null,"Column_4":null}