unordered-result
{"a_ida":10,"a1":3,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":15,"a1":4,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":25,"a1":6,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":30,"a1":7,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":35,"a1":8,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":10,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":20,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":30,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":40,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":50,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":2,"d_idc":5,"d_idd":5,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":2,"d_idc":5,"d_idd":10,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":3,"d_idc":6,"d_idd":10,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":10,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":12,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":4,"d_idc":12,"d_idd":10,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":15,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":20,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":25,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":6,"d_idc":20,"d_idd":25,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":6,"d_idc":25,"d_idd":30,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":6,"d_idc":25,"d_idd":35,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":8,"d_idc":25,"d_idd":30,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":8,"d_idc":25,"d_idd":35,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":9,"d_idc":5,"d_idd":30,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":35,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":40,"a1":9,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":45,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":true}
{"a_ida":45,"a1":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":55,"a1":12,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":60,"a1":13,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":65,"a1":14,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":70,"a1":15,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":75,"a1":16,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":80,"a1":17,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
{"a_ida":85,"a1":18,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"size_a_idx_c1":true,"size_d_idx_d2_idb_c3":null}
