ordered-result
{"c_ida":0,"c_idb":0,"c_idc":0,"a_ida":0,"a2":5,"b_ida":0,"b_idb":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":0,"c_idc":5,"a_ida":0,"a2":5,"b_ida":0,"b_idb":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":3,"c_idc":10,"a_ida":0,"a2":5,"b_ida":null,"b_idb":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":5,"c_idc":10,"a_ida":0,"a2":5,"b_ida":0,"b_idb":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":5,"c_idc":15,"a_ida":0,"a2":5,"b_ida":0,"b_idb":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":5,"c_idc":20,"a_ida":0,"a2":5,"b_ida":0,"b_idb":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":5,"c_idc":25,"a_ida":0,"a2":5,"b_ida":0,"b_idb":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":0,"c_idb":15,"c_idc":25,"a_ida":0,"a2":5,"b_ida":0,"b_idb":15,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30}
{"c_ida":0,"c_idb":15,"c_idc":25,"a_ida":0,"a2":5,"b_ida":0,"b_idb":15,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":35}
{"c_ida":10,"c_idb":8,"c_idc":10,"a_ida":10,"a2":42,"b_ida":null,"b_idb":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":40,"c_idb":0,"c_idc":0,"a_ida":40,"a2":35,"b_ida":40,"b_idb":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":40,"c_idb":2,"c_idc":5,"a_ida":40,"a2":35,"b_ida":null,"b_idb":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":40,"c_idb":4,"c_idc":7,"a_ida":40,"a2":35,"b_ida":null,"b_idb":null,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":10}
{"c_ida":40,"c_idb":4,"c_idc":7,"a_ida":40,"a2":35,"b_ida":null,"b_idb":null,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":12}
{"c_ida":40,"c_idb":4,"c_idc":10,"a_ida":40,"a2":35,"b_ida":null,"b_idb":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null}
{"c_ida":40,"c_idb":9,"c_idc":5,"a_ida":40,"a2":35,"b_ida":40,"b_idb":9,"d_ida":40,"d_idb":9,"d_idc":5,"d_idd":30}
{"c_ida":40,"c_idb":9,"c_idc":6,"a_ida":40,"a2":35,"b_ida":40,"b_idb":9,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":35}
{"c_ida":40,"c_idb":9,"c_idc":6,"a_ida":40,"a2":35,"b_ida":40,"b_idb":9,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":45}
