ordered-result
{"a_ida":95,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":20,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":0,"b_ida":0,"b_idb":0,"b_c1":8}
{"a_ida":0,"b_ida":0,"b_idb":5,"b_c1":8}
{"a_ida":0,"b_ida":0,"b_idb":10,"b_c1":9}
{"a_ida":0,"b_ida":0,"b_idb":15,"b_c1":9}
{"a_ida":5,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":50,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":90,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":25,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":30,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":40,"b_ida":40,"b_idb":0,"b_c1":9}
{"a_ida":40,"b_ida":40,"b_idb":5,"b_c1":8}
{"a_ida":40,"b_ida":40,"b_idb":6,"b_c1":null}
{"a_ida":40,"b_ida":40,"b_idb":7,"b_c1":null}
{"a_ida":40,"b_ida":40,"b_idb":8,"b_c1":null}
{"a_ida":40,"b_ida":40,"b_idb":9,"b_c1":null}
{"a_ida":45,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":10,"b_ida":10,"b_idb":4,"b_c1":null}
{"a_ida":85,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":35,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":75,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":15,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":65,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":70,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":80,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":55,"b_ida":null,"b_idb":null,"b_c1":null}
{"a_ida":60,"b_ida":null,"b_idb":null,"b_c1":null}
