unordered-result
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":6,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":7,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":4,"d_idc":10,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":35,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":35,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":0,"j_idg":15,"j_idj":25}
{"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":0,"j_idg":15,"j_idj":35}
{"a_ida":5,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":10,"j_idg":15,"j_idj":35}
{"a_ida":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":10,"j_idg":15,"j_idj":45}
{"a_ida":15,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":20,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":25,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":30,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":35,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":20,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":40,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":50,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":2,"d_idc":5,"d_idd":5,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":2,"d_idc":5,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":3,"d_idc":6,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":4,"d_idc":7,"d_idd":12,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":4,"d_idc":12,"d_idd":10,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":15,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":20,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":25,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":20,"d_idd":25,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":25,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":25,"d_idd":35,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":8,"d_idc":25,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":8,"d_idc":25,"d_idd":35,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":9,"d_idc":5,"d_idd":30,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":35,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":40,"d_idb":9,"d_idc":6,"d_idd":45,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":3,"j_idj":25}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":3,"j_idj":35}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":8,"j_idj":25}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":8,"j_idj":35}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":15,"j_idj":25}
{"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":40,"j_idg":15,"j_idj":35}
{"a_ida":45,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":50,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":55,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":60,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":65,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":70,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":75,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":80,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":85,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":90,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
{"a_ida":95,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"j_ida":null,"j_idg":null,"j_idj":null}
