unordered-result
{"a_ida":0,"b_ida":0,"b_idb":0,"g_ida":null,"g_idg":null}
{"a_ida":0,"b_ida":0,"b_idb":5,"g_ida":null,"g_idg":null}
{"a_ida":0,"b_ida":0,"b_idb":10,"g_ida":null,"g_idg":null}
{"a_ida":0,"b_ida":0,"b_idb":15,"g_ida":null,"g_idg":null}
{"a_ida":0,"b_ida":null,"b_idb":null,"g_ida":0,"g_idg":3}
{"a_ida":0,"b_ida":null,"b_idb":null,"g_ida":0,"g_idg":7}
{"a_ida":0,"b_ida":null,"b_idb":null,"g_ida":0,"g_idg":10}
{"a_ida":0,"b_ida":null,"b_idb":null,"g_ida":0,"g_idg":15}
{"a_ida":0,"b_ida":null,"b_idb":null,"g_ida":0,"g_idg":21}
{"a_ida":5,"b_ida":null,"b_idb":null,"g_ida":5,"g_idg":2}
{"a_ida":10,"b_ida":10,"b_idb":4,"g_ida":null,"g_idg":null}
{"a_ida":15,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":20,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":25,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":30,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":35,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":0,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":5,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":6,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":7,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":8,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":40,"b_idb":9,"g_ida":null,"g_idg":null}
{"a_ida":40,"b_ida":null,"b_idb":null,"g_ida":40,"g_idg":3}
{"a_ida":40,"b_ida":null,"b_idb":null,"g_ida":40,"g_idg":7}
{"a_ida":40,"b_ida":null,"b_idb":null,"g_ida":40,"g_idg":10}
{"a_ida":40,"b_ida":null,"b_idb":null,"g_ida":40,"g_idg":15}
{"a_ida":40,"b_ida":null,"b_idb":null,"g_ida":40,"g_idg":21}
{"a_ida":45,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":50,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":55,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":60,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":65,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":70,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":75,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":80,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":85,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":90,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
{"a_ida":95,"b_ida":null,"b_idb":null,"g_ida":null,"g_idg":null}
