unordered-result
{"ida":0,"Column_2":null,"idb":null,"idg":3}
{"ida":0,"Column_2":null,"idb":null,"idg":7}
{"ida":0,"Column_2":null,"idb":null,"idg":10}
{"ida":0,"Column_2":null,"idb":null,"idg":15}
{"ida":0,"Column_2":null,"idb":null,"idg":21}
{"ida":0,"Column_2":0,"idb":0,"idg":null}
{"ida":0,"Column_2":0,"idb":5,"idg":null}
{"ida":0,"Column_2":0,"idb":10,"idg":null}
{"ida":0,"Column_2":0,"idb":15,"idg":null}
{"ida":5,"Column_2":null,"idb":null,"idg":2}
{"ida":10,"Column_2":10,"idb":4,"idg":null}
{"ida":15,"Column_2":null,"idb":null,"idg":null}
{"ida":20,"Column_2":null,"idb":null,"idg":null}
{"ida":25,"Column_2":null,"idb":null,"idg":null}
{"ida":30,"Column_2":null,"idb":null,"idg":null}
{"ida":35,"Column_2":null,"idb":null,"idg":null}
{"ida":40,"Column_2":null,"idb":null,"idg":3}
{"ida":40,"Column_2":null,"idb":null,"idg":7}
{"ida":40,"Column_2":null,"idb":null,"idg":10}
{"ida":40,"Column_2":null,"idb":null,"idg":15}
{"ida":40,"Column_2":null,"idb":null,"idg":21}
{"ida":40,"Column_2":40,"idb":0,"idg":null}
{"ida":40,"Column_2":40,"idb":5,"idg":null}
{"ida":40,"Column_2":40,"idb":6,"idg":null}
{"ida":40,"Column_2":40,"idb":7,"idg":null}
{"ida":40,"Column_2":40,"idb":8,"idg":null}
{"ida":40,"Column_2":40,"idb":9,"idg":null}
{"ida":45,"Column_2":null,"idb":null,"idg":null}
{"ida":50,"Column_2":null,"idb":null,"idg":null}
{"ida":55,"Column_2":null,"idb":null,"idg":null}
{"ida":60,"Column_2":null,"idb":null,"idg":null}
{"ida":65,"Column_2":null,"idb":null,"idg":null}
{"ida":70,"Column_2":null,"idb":null,"idg":null}
{"ida":75,"Column_2":null,"idb":null,"idg":null}
{"ida":80,"Column_2":null,"idb":null,"idg":null}
{"ida":85,"Column_2":null,"idb":null,"idg":null}
{"ida":90,"Column_2":null,"idb":null,"idg":null}
{"ida":95,"Column_2":null,"idb":null,"idg":null}
