unordered-result
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":0,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":0,"c_ida":0,"c_idb":0,"c_idc":5,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":10,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":15,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":20,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":5,"c_ida":0,"c_idb":5,"c_idc":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":10,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":0,"a1":1,"b_ida":0,"b_idb":15,"c_ida":0,"c_idb":15,"c_idc":25,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":15,"a1":4,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":20,"a1":5,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":25,"a1":6,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":30,"a1":7,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":35,"a1":8,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":45,"a1":10,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":50,"a1":11,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":55,"a1":12,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":60,"a1":13,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":65,"a1":14,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":70,"a1":15,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":75,"a1":16,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":85,"a1":18,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":90,"a1":19,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
{"a_ida":95,"a1":20,"b_ida":null,"b_idb":null,"c_ida":null,"c_idb":null,"c_idc":null,"k_ida":null,"k_idg":null,"k_idj":null,"k_idk":null}
