ordered-result
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":0,"d_idd":0,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":5,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":5,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":6,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":0,"d_idb":0,"d_idc":7,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":0}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":5}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":6}
{"b_ida":0,"b_idb":0,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":0,"e_ide":7}
{"b_ida":0,"b_idb":5,"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":15,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":5,"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":10,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":5,"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":20,"d_idd":25,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":5,"a_ida":0,"d_ida":0,"d_idb":5,"d_idc":25,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":10,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":15,"a_ida":0,"d_ida":0,"d_idb":15,"d_idc":25,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":0,"b_idb":15,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":15,"e_ide":25}
{"b_ida":0,"b_idb":15,"a_ida":0,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":0,"e_idb":15,"e_ide":35}
{"b_ida":10,"b_idb":4,"a_ida":10,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":0,"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":10,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":0,"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":0,"a_ida":40,"d_ida":40,"d_idb":0,"d_idc":2,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":0,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":0,"e_ide":7}
{"b_ida":40,"b_idb":0,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":0,"e_ide":8}
{"b_ida":40,"b_idb":5,"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":15,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":5,"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":20,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":5,"a_ida":40,"d_ida":40,"d_idb":5,"d_idc":10,"d_idd":25,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":5,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":5,"e_ide":25}
{"b_ida":40,"b_idb":5,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":5,"e_ide":35}
{"b_ida":40,"b_idb":6,"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":20,"d_idd":25,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":6,"a_ida":40,"d_ida":40,"d_idb":6,"d_idc":25,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":7,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":25}
{"b_ida":40,"b_idb":7,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":35}
{"b_ida":40,"b_idb":7,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":7,"e_ide":45}
{"b_ida":40,"b_idb":8,"a_ida":40,"d_ida":40,"d_idb":8,"d_idc":25,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":8,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":8,"e_ide":25}
{"b_ida":40,"b_idb":8,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":8,"e_ide":35}
{"b_ida":40,"b_idb":9,"a_ida":40,"d_ida":40,"d_idb":9,"d_idc":5,"d_idd":30,"e_ida":null,"e_idb":null,"e_ide":null}
{"b_ida":40,"b_idb":9,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":25}
{"b_ida":40,"b_idb":9,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":35}
{"b_ida":40,"b_idb":9,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":45}
{"b_ida":40,"b_idb":9,"a_ida":40,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":40,"e_idb":9,"e_ide":55}
{"b_ida":41,"b_idb":10,"a_ida":null,"d_ida":null,"d_idb":null,"d_idc":null,"d_idd":null,"e_ida":null,"e_idb":null,"e_ide":null}
