unordered-result
{"id":0,"record":{"long":null,"int":20,"string":"aef","bool":true,"float":null},"info":{"address":{"city":"San Fransisco","phones":[{"areacode":408,"kind":"home","number":50},{"areacode":650,"kind":"work","number":51},{"areacode":null,"kind":"home","number":52},{"areacode":510,"kind":"home","number":53},{"areacode":415,"number":54},"650-234-4556",650234455],"state":"CA"},"age":10,"children":{"Anna":{"age":10,"friends":["Anna","John","Maria"],"school":"sch_1"},"Lisa":{"age":12,"friends":["Ada"]},"Mary":{"age":7,"friends":["Anna","Mark"],"school":"sch_3"}},"firstName":"first0","lastName":"last0"}}
{"id":8,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":{"city":"San Fransisco","phones":{"areacode":650,"kind":"work","number":80},"state":"CA"},"age":10,"children":{"Anna":null,"John":{"age":10,"friends":["Anna","John","Maria"],"school":"sch_1"},"Mary":7},"firstName":"first8","lastName":"last8"}}
{"id":7,"record":{"long":1,"int":-20,"string":"xyz","bool":true,"float":30.0},"info":{"address":{"city":"San Jose","phones":[{"areacode":408,"kind":"work","number":70},{"areacode":408,"kind":"work","number":71},{"areacode":408,"number":72},{"areacode":510,"kind":"home","number":73},{"areacode":415,"kind":"home","number":74}],"state":"CA"},"age":30,"children":{"Kathy":{"age":10,"friends":["Anna","Mark","Maria"],"school":"sch_3"},"Will":{"age":2,"friends":["Ada"],"school":"sch_1"}},"firstName":"first7","lastName":"last7"}}
{"id":1,"record":{"long":50,"int":20,"string":"xyz","bool":true,"float":3.0},"info":{"address":{"city":"Boston","phones":[{"areacode":304,"kind":"work","number":30},{"areacode":318,"kind":"work","number":31},{"areacode":400,"kind":"home","number":41},{"areacode":450,"kind":"home","number":43},{"areacode":480,"kind":"work","number":44},{"areacode":500,"kind":"work","number":51},{"areacode":520,"kind":"home","number":52},{"areacode":550,"kind":"home","number":53},{"areacode":560,"kind":"work","number":55}],"state":"MA"},"age":11,"children":{"Anna":{"age":9,"friends":["Bobby","John",null],"school":"sch_1"},"Dave":{"age":15,"friends":["Bill","Sam"],"school":"sch_3"},"Mark":{"age":4,"friends":["George"],"school":"sch_1"}},"firstName":"first1","lastName":"last1"}}
{"id":5,"record":{"long":2,"int":null,"string":"fg","bool":true,"float":-3.0},"info":{"address":{"city":"Salem","phones":[{"areacode":605,"kind":"work","number":60},{"areacode":520,"number":62}],"state":"MA"},"age":11,"children":{"Anna":{"age":29,"friends":["Bobby","Mark"],"school":"sch_1"},"Dave":{"age":16},"Julie":{"age":12,"school":"sch_2","scores":[1,3.5,4.2,2]},"Mark":{"age":14,"friends":["George"],"school":"sch_2"},"Tim":{"age":8,"hobbies":["football","tennis"],"school":"sch_2"}},"firstName":"first5","lastName":"last5"}}
{"id":4,"record":{"long":50,"int":10,"string":"abc","bool":false,"float":0.0},"info":{"address":{"city":"Salem","phones":[{"areacode":400,"kind":"home","number":41},{"areacode":460,"kind":"work","number":44},{"areacode":500,"kind":"work","number":50},{"areacode":570,"number":51},{"areacode":580,"number":51},{"areacode":600,"kind":"work","number":61},{"areacode":610,"kind":"home","number":62},{"areacode":620,"kind":"work","number":63}],"state":"MA"},"age":15,"children":{"Anna":{"age":9,"friends":["George","John"],"school":"sch_2"},"Mark":{"age":9,"friends":["George"],"school":"sch_1"}},"firstName":"first4","lastName":"last4"}}
{"id":6,"record":{"long":null,"int":null,"string":"ef","bool":true,"float":3.0},"info":{"address":{"city":"Albany","phones":[{"areacode":605,"kind":"work","number":60},{"areacode":629,"kind":"work","number":62}],"state":"NY"},"age":11,"firstName":"first6","lastName":"last6"}}
{"id":2,"record":{"long":50,"int":50,"string":"abc","bool":false,"float":33.0},"info":{"address":{"city":"Portland","phones":[{"areacode":104,"kind":"home","number":10},{"areacode":118,"kind":"work","number":11}],"state":"OR"},"age":12,"children":{},"firstName":"first2","lastName":"last2"}}
{"id":3,"record":{"long":10,"int":200,"string":"tr","bool":true,"float":3.0},"info":{"address":{"city":"Seattle","phones":null,"state":"WA"},"age":13,"children":{"George":{"age":7,"friends":["Bill","Mark"],"school":"sch_2"},"Matt":{"age":14,"friends":["Bill"],"school":"sch_2"}},"firstName":"first3","lastName":"last3"}}
{"id":11,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":{"city":"Portland","phones":{"areacode":408,"kind":"work","number":80}},"children":{"Anna":{"age":10,"school":"sch_1"},"Lisa":null,"Mary":7},"firstName":"first8","lastName":"last8"}}
{"id":10,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":{"city":"San Fransisco","phones":{"areacode":408,"number":80}},"age":null,"children":{"Anna":{"age":10,"friends":[],"school":"sch_1"},"Lisa":null,"Mary":7},"firstName":"first8","lastName":"last8"}}
{"id":17,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":"somewhere","age":10,"children":"none","firstName":"first8","lastName":"last8"}}
{"id":15,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":null}
{"id":16,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":null}
{"id":12,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":{"city":"San Fransisco","phones":{"areacode":408,"kind":"home","number":80},"state":null},"children":{"Anna":{"age":10,"friends":null,"school":"sch_2"},"Lisa":null,"Mary":7},"firstName":"first8","lastName":"last8"}}
{"id":9,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":{"address":{"city":"San Fransisco","phones":{"areacode":408,"kind":"work","number":80},"state":null},"age":null,"children":{"Anna":7,"John":{"age":10,"friends":["Anna","John","Maria"],"school":"sch_1"},"Lisa":null},"firstName":"first8","lastName":"last8"}}
{"id":13,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":null}
{"id":14,"record":{"long":0,"int":20,"string":"abc","bool":true,"float":3.0},"info":null}
