ordered-result
{"id":15,"state":3}
{"id":14,"state":3}
{"id":20,"state":3}
{"id":8,"state":4}
{"id":18,"state":5}
{"id":19,"state":5.3}
{"id":21,"state":""}
{"id":0,"state":"CA"}
{"id":7,"state":"CA"}
{"id":1,"state":"MA"}
{"id":5,"state":"MA"}
{"id":4,"state":"MA"}
{"id":6,"state":"NY"}
{"id":22,"state":"OR"}
{"id":23,"state":"OR"}
{"id":24,"state":"OR"}
{"id":28,"state":"OR"}
{"id":2,"state":"OR"}
{"id":25,"state":"OR"}
{"id":3,"state":"WA"}
{"id":27,"state":false}
{"id":26,"state":true}
{"id":11,"state":"EMPTY"}
{"id":10,"state":"EMPTY"}
{"id":17,"state":"EMPTY"}
{"id":16,"state":"EMPTY"}
{"id":12,"state":null}
{"id":9,"state":null}
{"id":13,"state":"NULL"}
